package com.example.demo.retirement.ai;

import java.util.List;

/**
 * Structured narrative produced by the LLM for a whole retirement plan.
 *
 * @param executiveSummary one-paragraph summary for the customer
 * @param overallInsights  long-form analysis (profile, adequacy, strategy phases)
 * @param recommendedMaturityOption one of ANNUITY / LUMP_SUM / REINVEST
 * @param yearNarratives   per-year advice, one entry per projected year
 */
public record AiRetirementNarrative(
        String executiveSummary,
        String overallInsights,
        String recommendedMaturityOption,
        List<AiYearNarrative> yearNarratives) {

    /**
     * Per-year advice generated by the model.
     *
     * @param year           1-based year of retirement
     * @param recommendation narrative guidance for that year
     * @param mixMatchOption mix-match label, e.g. "REINVEST - ..."
     */
    public record AiYearNarrative(Integer year, String recommendation, String mixMatchOption) {
    }

    /** @return narrative for the requested year, or {@code null} when absent. */
    public AiYearNarrative narrativeForYear(int year) {
        if (yearNarratives == null) {
            return null;
        }
        return yearNarratives.stream()
                .filter(n -> n != null && n.year() != null && n.year() == year)
                .findFirst()
                .orElse(null);
    }
}